import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { BIZ_UDPGothic } from "next/font/google";

const bizUDPGothic = BIZ_UDPGothic({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-biz-ud-p-gothic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bizUDPGothic.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
